removePreviousWindows=false

[Workspaces]
monitor0=1 3
monitor1=2 4

[Workspace 1]
alacritty

[Workspace 2]
omarchy-launch-browser


[Workspace 3]
omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

[Workspace 4]
omarchy-launch-or-focus-webapp AppleMusic "https://music.apple.com/de/home/"
uwsm-app -- thunderbird --mail
